
version: '2'

networks:
  cbNetwork:
    driver: bridge

services:
  db:
    image: betagouv/api-meds-db
    hostname: couchbase.meds
    container_name: couchbase.meds
    networks:
      - cbNetwork
    ports:
      - 8091-8094:8091-8094
      - 11210:11210

  api:
    image: betagouv/api-meds-api
    environment:
      cb_connectionString: couchbase://couchbase.meds:8091
    networks:
      - cbNetwork
    depends_on:
      - db
    hostname: api.med
    container_name: api.med
    ports:
      - 3004:3004
    command: bash -c "sleep 30 && npm start"
